# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18.10.0
        cache: 'npm'
    
    - run: npm i @yaakovhatam/take-npm-packages
    - run: npm i 
    - run: npx @yaakovhatam/take-npm-packages --subdeps
    - run: npm run build --if-present
    - run: npm test --if-present
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
          name: artifact node_modules
          path: |
            node_modules
