# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18.10.0
        cache: 'npm'
    
    - name: check folder
      run: echo ${{ env }} ${{ secrets.HAMAMA_SENDGRID_API_KEY}} ${{ secrets.HAMAMA_SENDGRID_API_KEY.HAMAMA_SENDGRID_API_KEY}}
    - name: Send mail
      run: >
          curl --request POST 
          --url https://api.sendgrid.com/v3/mail/send 
          --header "Authorization: Bearer ${{ secrets.HAMAMA_SENDGRID_API_KEY}}" 
          --header 'Content-Type: application/json' 
          --data '{"personalizations": [{"to": [{"email": "yoni333@gmail.com"}]}],"from": {"email": "hamamaoutworld@gmail.com"},"subject": "Sending with SendGrid is Fun","content": [{"type": "text/plain", "value": "and easy to do anywhere, even with cURL"}]}'
    - run: npm i @yaakovhatam/take-npm-packages
    - run: npm i 
    - run: npx @yaakovhatam/take-npm-packages --subdeps
    - name: Build angular
      working-directory: ./
      run: npm run build --if-present
    - name: check after working direcotry
      run: echo ${{ env }}
    - name: Archive production artifact   s
      uses: actions/upload-artifact@v3
      with:
          name: artifact node_modules
          path: |
            node_modules
