# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    environment: HAMAMA_SENDGRID_API_KEY
    steps:
    - name: check folder
      shell: bash
      run: |
             echo ${{ env.SENDER_EMAIL }} 
             echo ${{ secrets.HAMAMA_SENDGRID_API_KEY}}
             echo $HAMAMA_SENDGRID_API_KEY
             echo ${{ github.repository }}
           
           

         
      env:
        HAMAMA_SENDGRID_API_KEY: ${{ secrets.HAMAMA_SENDGRID_API_KEY}}
       
    
    - name: Send mail 2
      env:
        SENDGRID_API_KEY: ${{ secrets.HAMAMA_SENDGRID_API_KEY }}
      run: |
        curl --request POST \
        --url https://api.sendgrid.com/v3/mail/send \
        --header "Authorization: Bearer $SENDGRID_API_KEY" \
        --header 'Content-Type: application/json' \
        --data '{
            "personalizations": [
            {
                "to": [
                {
                    "email": "yoni333@gmail.com"
                }
                ],
                "subject": "Hello, World!"
            }
            ],
            "from": {
            "email": "hamamaoutworld@gmail.com"
            },
            "content": [
            {
                "type": "text/plain",
                "value": "Hello, World!"
            }
            ]
        }'
    